#lang ivy1.7

type client
type server

relation link(X:client, Y:server)
relation semaphore(X:server)

after init {
    semaphore(W) := true;
    link(X,Y) := false
}

action connect(x:client,y:server) = {
  require semaphore(y);
  link(x,y) := true;
  semaphore(y) := false
}

action disconnect(x:client,y:server) = {
  require link(x,y);
  link(x,y) := false;
  semaphore(y) := true
}

invariant ~(X ~= Z & link(X,Y) & link(Z,Y)) 
#Should allow 1 client connecting at the server at any time

export connect
export disconnect

# Add this to prove the invariant
#This says that there is no client X and server Y such that X is linked to Y and the semaphore at Y is up
private {
   # invariant ~(link(X,Y) & semaphore(Y))
}
